# Welcome to Jekyll!
#

# Site settings
title: Agencia de Viajes ReGil
description: |
  Bienvenid@ a "Agencia de viajes ReGil" en donde podrás encontrar los mejores servicios 
owner: Reynoso Gil Melina # or company name
first_published: 2022 # if migrating another site, the year of your first publish
email: melina.rgil.17@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  facebook-official: https://www.facebook.com/melina.gil.988/<username>
  
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
